### ISSUE TITLE
계산기 과제(필수) 피드백

### ISSUE THREAD

**Issue by ssk910** [parkmookeun/sparta_calc_essential#1]
# 1. Git

## 1.1. 커밋 메세지

커밋 메세지는 사소해 보이지만, **생각보다 개발자들이 중요하게 여기는 부분**입니다. \
개발하다보면 시간이 없어서, 귀찮아서 제대로 작성하지 못하는 경우가 많은데 초기에 습관을 들이시면 큰 도움이 되실 것 같습니다. \
나중에 나의 업무를 되돌아보거나 정리할 때, 이전 이력으로 되돌아가고 싶을 때 이 커밋 메세지가 굉장히 유용하니 아주 자세히는 아니더라도 풍부하게 커밋 메세지를 작성해주세요!

- [커밋 컨벤션의 중요성을 언급한 아티클](https://yozm.wishket.com/magazine/detail/1974/)
- [커밋 컨벤션에 대한 설명](https://hyunjun.kr/21)

## 1.2. .gitignore

- `.gitignore` 파일을 활용해 보시는 것을 추천합니다. 이 파일은 특정 디렉토리나 파일들을 git에 추가를 막아 그 파일들이 실수로 커밋되지 않도록 하는 역할을 합니다. 
  - [`.gitignore`에 대한 간단한 설명](https://sunhyeokchoe.github.io/posts/Ignoring-Files/)
- 프로젝트의 루트 디렉토리에 있는 **`.idea` 폴더는 IDE인 IntelliJ Idea가 자체 설정을 위해 생성해 주는 폴더**입니다. \
따라서 이 폴더는 `.gitignore` 파일에 추가해서 커밋되지 않도록 막으면 더욱 좋습니다.
  - 사용중인 OS, IDE 정보를 입력하면 이에 알맞는 `.gitignore`를 생성해주는 오픈소스도 있으니 한번 확인해보세요!
  - https://www.toptal.com/developers/gitignore

----

# 2. README 문서

README 문서는 오픈 소스를 이용하거나, 큰 프로젝트에 참여하지 않았다면 중요성이 체감되지 않을 수 있습니다.
[이 아티클](https://www.freecodecamp.org/korean/news/gisheobeu-peurojegteue-rideumi-paileul-jal-jagseonghaneun-bangbeob/)에서 README에 대해 잘 설명해주고 있으니, 읽어보시면 큰 도움이 될 것 같습니다.

아시다시피 이 파일의 확장자는 .md이며, md는 "Markdown"의 약자입니다.
텍스트 파일의 여러가지 종류 중에 마크다운 문법으로 작성하는 파일이 있고, 바로 md 파일이 이에 해당합니다.

[마크다운 문법](https://docs.github.com/ko/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)이라니 좀 생소하시죠? 알아두면 나중에 여러모로 쓸모가 많은 녀석입니다.
문법에 맞게 특수기호를 섞어서 글을 작성하고 나면, 한글이나 워드 파일로 편집한 것처럼 보기 좋게 보이게 됩니다.
저도 지금 이 글을 마크다운 문법으로 작성하고 있습니다! 대부분의 README 문서는 마크다운 문법을 활용하고 있으니 여유가 되신다면 간단하게 보셔도 좋습니다.

다른 오픈 소스 프로젝트의 README 문서를 참고해서 어떤 내용을 추가하면 좋은지 살펴봐도 좋습니다.
(이번 과제 프로젝트는 README를 자세하게 쓸 수 있을 만큼의 범위는 아니지만, 나중에 도움이 되셨으면 합니다)

예시:
- https://github.com/naver/fixture-monkey
- https://github.com/naver/ngrinder

----

# 3. 코드

### 3.1.1 개행을 이용하여 코드 묶기

개행으로 일부 코드를 묶음으로 나타내면 코드의 분석이 쉬워집니다. 코드의 분석이 쉬워진다는 것은 유지보수성이 높아진다는 것을 의미합니다. \
유지보수가 왜 중요할까요? 왜냐하면 우리는 다른 개발자들과 함께 일하므로 **다른 사람의 코드를 읽는 데에 더 많은 시간을 사용합니다.** \
그러므로 코드를 작성할 때 항상 이 점을 생각하면서 작성하시다보면, 함께 일하고 싶은 개발자가 되어 있으실 겁니다.

위에서 말한 것처럼 개행을 이용하여 [Main 클래스](https://github.com/parkmookeun/sparta_calc_essential/blob/main/Main.java)를 조금 수정해 보겠습니다.
```java
public class Main {
    public static void main(String[] args) {
        int result = 0;
        String operations = "+-*/";

        while (true) {
            Scanner sc = new Scanner(System.in);            
            System.out.print("사칙연산 기호를 입력하세요: ");
            String input = sc.next();

            if (input.equals("exit")) {
                System.out.println("연산을 종료합니다...");
                break;
            }

            char op = input.charAt(0);
            while (!operations.contains(String.valueOf(op))) {
                System.out.println("연산 기호를 다시 입력해주세요!");                
                System.out.print("사칙연산 기호를 입력하세요: ");
                input = sc.next();
                
                if (input.equals("exit")) {
                    System.out.println("연산을 종료합니다...");
                    return;
                }                
                op = input.charAt(0);
            }
            
            System.out.print("첫번째 수: ");
            int num1 = sc.nextInt();
            
            System.out.print("두번째 수: ");
            int num2 = sc.nextInt();
            
            while (op == '/' && num2 == 0) {
                System.out.println("0으로 나눌 수 없습니다!");
                System.out.print("두번째 수: ");
                num2 = sc.nextInt();
            }

            switch (op) {
                case '+':
                    result = num1 + num2;
                    break;
                case '-':
                    result = num1 - num2;
                    break;
                case '*':
                    result = num1 * num2;
                    break;
                case '/':
                    result = num1 / num2;
                    break;
            }
            
            System.out.println("연산 결과: " + result);
        }
    }
}
```

**코드의 묶음은 우리가 읽는 글의 단락과 비슷합니다.** 코드를 개행으로 구분하고, 묶음으로써 하나의 생각 덩어리 또는 로직을 표현하여 글을 읽듯이 코드를 읽을 수 있게 됩니다.

### 3.1.2. `contains()` 메소드를 이용하여 문자열 찾기

`Main` 클래스의 21번 라인에서 다음과 같이 사칙 연산 기호를 찾는 로직이 있습니다.
```java
String operations = "+-*/";

/* ... 중략 ... */

            while (!operations.contains(String.valueOf(op))) {
                // ...
            }
```

`String`의 `contains()` 메소드를 사용함으로써 코드가 간결해졌습니다. 여기서 말씀드리고 싶은건 사용하고자 하는 것은 "메소드의 퍼포먼스를 고려하면 좋다"라는 점입니다.
`String` 클래스의 `contains()` 메소드를 정의한 실제 코드를 보면 아래와 같이 작성되었습니다.
```java
  public boolean contains(CharSequence s) {
        return indexOf(s.toString()) >= 0;
    }
```
그리고 여기서 사용된 `indexOf()` 메소드를 좀 더 파고들어가면 아래와 같이 되어있습니다.
```java
  public static int indexOf(byte[] value, int valueCount, byte[] str, int strCount, int fromIndex) {
        byte first = str[0];
        int max = (valueCount - strCount);
        for (int i = fromIndex; i <= max; i++) {
            // Look for first character.
            if (value[i] != first) {
                while (++i <= max && value[i] != first);
            }
            // Found first character, now look at the rest of value
            if (i <= max) {
                int j = i + 1;
                int end = j + strCount - 1;
                for (int k = 1; j < end && value[j] == str[k]; j++, k++);
                if (j == end) {
                    // Found whole string.
                    return i;
                }
            }
        }
        return -1;
    }
```
보시다시피 문자열에서 원하는 문자를 찾기 위해 **2중 `for문**을 사용하고 있습니다.
물론 과제처럼 작은 프로그램에서는 크게 나타나지는 않겠지만, 나중에는 이렇게 퍼포먼스와 메모리에 끼치는 영향을 고려하여 사용하시면 더욱 안전한 프로그램을 작성하실 수 있습니다!

### 3.2.1. [`Calculator` 클래스의 `calculate()` 메소드](https://github.com/parkmookeun/sparta_calc_essential/blob/a39ed59d787bbb187992e09cfdebc2bb833665d4/Calculator.java#L23-L53) 리팩토링

이 메소드를 좀 더 살펴보면 개선할 수 있는 포인트가 있습니다. 메소드에서 수행되는 로직은 다음과 같이 정리해 볼 수 있습니다.
1. 사칙연산 기호가 맞는지 체크한다.
2. 나눗셈의 경우 분모가 0인지 체크한다.
3. 사칙연산 기호에 따라 알맞는 연산을 수행한다.
4. 연산 결과를 Queue에 추가한다.

위에서 1번과 2번을 3번 로직에 엣지 케이스로 함께 묶을 수 있습니다.
1. 사칙연산 기호에 따라 알맞는 연산을 수행한다.
    1. 나눗셈의 경우 분모가 0이면 수행을 종료한다.
    2. 사칙연산 기호가 아니면 수행을 종료한다.
2. 연산 결과를 Queue에 추가한다.

새롭게 정리한 로직대로 메소드를 수정해보았습니다.
```java
    public void calculate(char op, int num1, int num2) {
        int result = 0;

        switch (op) {
            case '+':
                result = num1 + num2;
                break;
            case '-':
                result = num1 - num2;
                break;
            case '*':
                result = num1 * num2;
                break;
            case '/':
                if (num2 == 0) {
                    System.out.println("0으로 나눌 수 없습니다!");
                    return;
                }
                
                result = num1 / num2;
                break;
            default:
                System.out.println("사칙연산자 기호를 입력하세요!");
                return;
        }

        System.out.println("연산 결과: " + result);
        list.add(result);
        System.out.println("현재 리스트: " + list.toString());
    }
```
여기서 0으로 나눌 수 없거나 사칙연산 기호가 아닌 경우에는 `Exception`을 던져서 예외처리도 할 수 있으니, 나중에 살펴보시기 바랍니다.

### 3.2.2. 엣지 케이스

`List`가 비어 있는 경우, 나눗셈의 분모가 0인 경우, 연산자가 아닌 경우 등과 같이 \
예외의 케이스를 생각하여 처리하는 것은 아주 좋았습니다! `if`가 있다면 반드시 `else`의 경우일 때 어떻게 처리해야 할지 고민하면 좋은데 이미 잘 하고 계신 것 같습니다!

----

# 4. 코드 컨벤션 및 변수명

- 처음 개발을 접하신 것임에도 불구하고, 코드 컨벤션을 잘 지켜주셨습니다. \
많은 초보 개발자들이 잘 신경쓰지 않거나 모르는 부분인데 잘 해주셨습니다.
- 변수명은 조금 더 명확하게 지으시면 좋을 것 같습니다. \
이름만 봐도 무슨 역할인지 직관적으로 잘 지어주신다면, 다른 개발자들과 협업을 할 때 이 변수의 이름 하나로 유지보수가 굉장히 쉬워집니다.

아래의 링크들도 한 번 간단하게 훑어보시면 도움이 되실 것 같습니다.

- 네이버가 사용하는 컨벤션: https://naver.github.io/hackday-conventions-java/
- 구글이 사용하는 컨벤션: https://sihyung92.oopy.io/af26a1f6-b327-45a6-a72b-c6fcb754e219

**Comment by parkmookeun** [comment]
피드백 감사합니다!!!
